[tool.poetry]
name = "ribbons-of-democracy"
version = "0.1.0"
description = ""
authors = ["Charlie Rogers <charlie.rogers@fearnworks.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
